let appPhrases = [
  'Y es que contigo quiero vivir todo eso que no he vivido con alguien más, quiero proponerte todos los planes que jamás he propuesto, quiero leerte, cantarte y cuidarte, quiero abrazarte cada tarde, quiero llorar de felicidad. Y es que contigo solo busco poder hacer las cosas bien, por primera vez, porque quiero, porque eres tú, porque es contigo🥰.',
  'Que sepas que eres valiente y capaz 🌟 no hay reto que no puedas superar 💪 y quiero verte brillar ✨.',
  'Que sepas que eres tan hermosa que el mundo parece detenerse un momento 💘 tu belleza no solo se ve, se siente 💞.',
  'Permíteme decirte que tienes un corazón gigante ❤️ mereces lo mejor siempre 🌹 y quiero verte sonreír siempre 😊.',
  'Y es que contigo quiero vivir todo eso que no he vivido con alguien más, quiero proponerte todos los planes que jamás he propuesto, quiero leerte, cantarte y cuidarte, quiero abrazarte cada tarde, quiero llorar de felicidad. Y es que contigo solo busco poder hacer las cosas bien, por primera vez, porque quiero, porque eres tú, porque es contigo🥰.',
  '🌞 Cada amanecer trae una oportunidad para ser feliz, y pensar en ti ya hace que el día empiece bien 💕.',
  'Hoy no es un día cualquiera, es otro día en el que puedo agradecer por tu existencia. Eres esa calma que transforma lo cotidiano en algo especial. 💫',
  'A veces la vida se siente pesada, pero quiero que sepas que no estás sola. Si algún día dudas, piensa en lo mucho que vales y en cómo tu sonrisa puede cambiar el rumbo de todo. ❤️',
  'Esther, hay personas que llegan para quedarse sin necesidad de promesas, solo porque su esencia ilumina. Tú eres una de ellas. 🌙',
  'Si hoy el día se complica, recuerda que has superado cosas más difíciles. Tu fortaleza y ternura son una combinación que inspira. 🌻',
  'A veces pienso que la Luna se siente afortunada cuando la miras, porque pocas cosas brillan tanto como tú cuando sonríes. 🌕',
  'Hoy quiero recordarte lo valiosa que eres, no solo por lo que haces, sino por lo que transmites. Eres esa chispa que enciende esperanza en los demás. 🔥',
  'Ojalá este día te regale un motivo para reír, uno para soñar y otro para seguir creyendo en lo bonito de la vida. 💫',
  'Hay personas que cambian el clima con su presencia. Tú eres como un amanecer después de una larga noche. 🌅',
  'Si supieras lo mucho que pienso en ti cuando miro el cielo, entenderías que hay días donde la distancia se siente menos cuando te tengo en mis pensamientos. ☁️',
  'Nunca dejes que las dudas apaguen lo que brilla en ti. Tu forma de ver el mundo es un recordatorio de que aún hay luz entre tanta prisa. 🌟',
  'Hoy quiero agradecerte, aunque no lo sepas. Porque con solo existir, haces que los días tengan más sentido. 🌸',
  'Hay cosas que no se explican, solo se sienten. Y lo que tú generas, va más allá de las palabras. 💖',
  'Tómate un momento para respirar, mirar al cielo y recordar lo lejos que has llegado. Eres más fuerte de lo que imaginas. 💪🏼',
  'Si hoy sientes cansancio, no olvides que incluso el sol necesita descansar para volver a brillar. 🌞',
  'Hoy no busques perfección, solo busca sentirte en paz. Lo demás llegará, como llega la brisa después del calor. 🌬️',
  'Cuando la vida se sienta pesada, recuerda lo mucho que vales. No hay tormenta que pueda con un corazón tan noble como el tuyo. 🌧️❤️',
  'A veces lo mejor del día es ese pequeño instante en el que piensas en alguien y sonríes. Tú eres ese instante para mí. 😊',
  'Esther, ojalá pudieras verte con mis ojos, entenderías por qué cada día me inspiras a ser mejor. 🌙',
  'Hay miradas que calman, palabras que abrazan y personas que cambian todo sin saberlo. Tú eres las tres cosas a la vez. 💫',
  'No dejes de perseguir tus sueños, incluso los más pequeños. El universo siempre conspira a favor de quienes aman con el corazón. 🌠',
  'Hoy la Luna brilla distinto, o quizás soy yo que no puedo dejar de pensar en ti cuando la veo. 🌕',
  'Nunca olvides que tu presencia tiene un impacto. Donde estás, algo mejora, algo florece. 🌸',
  'Si hoy te sientes cansada, recuerda que el simple hecho de seguir intentando ya es una forma de valentía. 🌈"',
  'No hay días vacíos si los llenas con tu luz. Eres una de esas almas que dejan huella sin intentarlo. ❤️',
  'Cuando la rutina te abrume, recuerda que no necesitas hacer mucho para ser especial. Tú ya lo eres, solo por ser tú. 🌙',
  'Hoy quiero que sonrías sin razón, porque el mundo se vuelve un poco más bonito cuando lo haces. 😌',
  'Gracias por ser inspiración constante, incluso en los días en que el sol no sale. 🌦️',
  'Si el día se siente gris, piensa en todo lo que has superado y en la luz que llevas dentro. Eres increíble, Esther. 💫',
  "🌤️ Eres esa chispa que ilumina los días más nublados. Si el mundo se apaga, sé que bastaría con verte sonreír para volver a encenderlo todo ❤️.",
  "🎶 A veces me basta con imaginarte riendo para sentir paz. No hay melodía más suave que tu alegría llenando mi pensamiento 💭.",
  "🌻 Me inspiras a ser mejor, a crecer, a no rendirme. Es increíble cómo alguien puede motivar tanto con solo existir. Eso haces tú, Esther ✨.",
  "☕ Hay días en los que el cansancio pesa, pero pienso en ti y se me olvida todo. Eres mi recordatorio de que las cosas buenas siempre valen la pena 💕.",
  "💪 Si supieras lo mucho que admiro tu fuerza, entenderías por qué te veo como una persona increíble. Eres capaz de tanto más de lo que imaginas 💫.",
  "🙏 Hoy quiero agradecerle al destino por haberte cruzado en mi camino. Hay personas que llegan para cambiarlo todo, y tú fuiste una de ellas 💖.",
  "🌙 Nada me resulta más reconfortante que saber que existes, Esther. Porque aunque los días sean difíciles, pensarte siempre me devuelve la calma 🌌.",
  "🌈 Si el cielo pudiera hablar, seguramente contaría lo afortunado que soy de poder pensar en ti cada día. Eres mi pensamiento favorito 💭❤️.",
  "😄 Nunca subestimes el poder de tu sonrisa; tiene la magia de cambiar el rumbo de un día entero. Hoy, como siempre, deseo verte sonreír 🌞.",
  "✨ Hay algo en ti que no se explica, solo se siente. Y lo que siento cada vez que pienso en ti, es una mezcla de paz y emoción 💕.",
  "🔥 Eres esa inspiración que llega sin aviso, pero que transforma todo. Desde que te conozco, cada meta parece más posible 💫.",
  "🌅 Me gusta pensar que cada mañana el universo te sonríe igual que yo lo hago al recordarte. Porque mereces todo lo bonito del día ❤️.",
  "🌹 Si la vida me da la oportunidad de coincidir contigo una y otra vez, la tomaría sin pensarlo. Hay conexiones que simplemente valen todo 🥰.",
  "🎨 Tu forma de ver el mundo es un arte. Logras encontrar belleza en lo simple, y eso me enseña a mirar distinto cada día 💐.",
  "🌟 Eres ese tipo de persona que deja huellas sin hacer ruido, que inspira sin intentarlo, que ilumina sin buscar ser el centro. Así de especial eres tú 💫.",
  "☀️ Hoy solo deseo que tengas un día tan bonito como tu forma de ser. Que todo te salga bien, y que recuerdes que hay alguien que te admira mucho 🩷.",
  "🌙 Cada vez que veo la luna, pienso que ella también te observa y entiende por qué me gusta tanto hacerlo. Brillas como ella, pero más cerquita 💫.",
  "🕊️ A veces la vida se vuelve rutina, pero basta una conversación contigo para sentir que todo tiene sentido otra vez 💬❤️.",
  "💖 Tu nombre siempre me suena a calma, a luz, a algo que quiero cuidar. Gracias por ser esa energía tan bonita en mis días ☀️.",
  "🌼 No hay duda de que eres alguien especial, Esther. Lo sé porque el simple hecho de pensar en ti ya mejora cualquier día 💕.",
  "🌠 No sé si el destino se equivoca, pero contigo siento que por fin hizo algo bien. Y cada día le agradezco por eso 🙏.",
  "💞 Hay personas que te cambian el ánimo, tú me cambias la vida. Sin hacer nada, solo siendo tú ✨.",
  "🏆 Cada vez que cumples una meta, me siento orgulloso. Porque sé lo mucho que te esfuerzas, y mereces todo lo que logras 💪💖.",
  "🕯️ La vida se trata de momentos, y los más bonitos siempre terminan llevándome a ti 💫.",
  "🎇 Ojalá pudieras verte con mis ojos, entenderías lo increíble que eres, lo mucho que vales y lo feliz que haces a quienes te rodean 🌹.",
  "🌻 Cuando sonríes, el mundo se acomoda un poquito mejor. No sé si lo notas, pero tienes ese poder tan tuyo, tan único 💫.",
  "🌙 Me gusta pensar que, incluso a la distancia, la luna lleva mis pensamientos hacia ti 💭❤️.",
  "🌈 Nunca olvides lo mucho que vales. No necesitas ser perfecta, ya eres suficiente solo siendo tú 💕.",
  "Hay días en los que todo parece igual, pero basta con pensar en ti para que todo se vuelva especial ❤️",
  "No hay distancia ni tiempo que cambie lo que provocas en mí, porque sigues siendo mi pensamiento favorito 💭💖",
  "Tu sonrisa tiene ese poder mágico de transformar cualquier día gris en uno lleno de color 🎨🌈",
  "Si alguna vez dudas de ti, recuerda que hay alguien aquí que cree en ti más de lo que imaginas 🌟",
  "Hay personas que llegan sin aviso y se vuelven imposibles de olvidar… tú eres una de ellas 💕",
  "Cada palabra tuya deja huella, cada mirada tuya deja calma… eres mi inspiración de todos los días ✨",
  "Hoy quiero recordarte lo valiosa que eres, por dentro y por fuera 🌹 no cambies nunca esa esencia tan tuya 💫",
  "A veces no lo digo, pero tu forma de ser me encanta… tu forma de ver el mundo me inspira 🌍❤️",
  "Eres esa calma que mi corazón busca cuando todo parece ir demasiado rápido 💫",
  "Me basta un mensaje tuyo para sonreír todo el día 😊 gracias por existir, simplemente eso ❤️",
  "Nunca dejes que las dudas apaguen tu brillo, porque tú naciste para brillar con luz propia ✨",
  "Tu voz, tu risa, tu forma de ver las cosas… todo en ti tiene algo que me atrapa 💫",
  "Hay personas que se vuelven hogar sin darte cuenta, y tú eres mi lugar favorito 🏡💖",
  "Tu presencia tiene ese efecto mágico que hace que todo se sienta bien, incluso lo que antes no lo estaba 🌷",
  "Hoy solo quiero desearte un día lleno de paz, amor y cosas bonitas, porque te lo mereces todo 🌞",
  "Tus sueños son tan grandes como tu corazón, y sé que vas a alcanzarlos todos 🌙💪🏼",
  "Cada vez que pienso en ti, el mundo parece detenerse un instante… y en ese momento todo cobra sentido 💫",
  "No hay palabra suficiente para describir lo bien que me haces sentir solo con existir 🌻",
  "A veces la vida te regala personas increíbles sin razón aparente, y tú eres ese regalo para mí 🎁💖",
  "Tu luz no solo ilumina tus días, también los míos ✨ nunca dejes de brillar así ❤️",
  "Si alguna vez sientes que el día es difícil, recuerda que alguien aquí cree totalmente en ti 🌟",
  "Gracias por ser esa persona que inspira calma, ternura y ganas de ser mejor 💫",
  "Junio está lleno de momentos, pero el mejor de todos siempre será pensar en ti 💕",
  "Hay algo en ti que me da paz, algo que me hace querer quedarme un poco más en cada conversación 🌙",
  "No importa lo que pase, siempre voy a desearte lo mejor, porque te lo mereces todo y más 💫",
  "Eres como ese amanecer que anuncia que todo estará bien, aún después de la noche más larga ☀️❤️",
  "Tu forma de ser, tan única, me recuerda que hay belleza en las cosas simples… y tú eres la prueba 🌸",
  "☀️ Hay algo en ti, Esther, que transmite calma incluso en los días más pesados. Eres mi pensamiento bonito de cada mañana ❤️.",
  "🌸 No sé si lo notas, pero cuando sonríes, el mundo parece un poco más amable 💕.",
  "🌻 Las personas más especiales son las que no buscan brillar, y aun así iluminan todo a su alrededor. Tú eres así ✨.",
  "💫 Cada día que pasa confirmo que hay algo en ti que simplemente me inspira a ser mejor 🌈.",
  "🌙 Hay noches en las que miro el cielo y me pregunto si también estás viendo la misma luna. Es mi forma de sentirte cerca 💭.",
  "🌼 Que hoy el universo te regale razones para sonreír y motivos para creer en ti. Lo mereces todo 💕.",
  "☕ Cada día tiene su magia, pero cuando pienso en ti, se siente distinto… más bonito, más real 💖.",
  "🌹 No hay nada más admirable que ver cómo sigues adelante, incluso cuando las cosas se complican. Eres fortaleza pura 💪.",
  "❤️ Si la vida fuera un jardín, tú serías la flor que más destaca, no por ser perfecta, sino por ser auténtica 🌻.",
  "✨ A veces no entiendo cómo lo haces, pero siempre logras dejar una sensación bonita incluso con tus palabras más simples 💫.",
  "🌈 No todos los días tienen que ser extraordinarios, pero tú haces que los míos siempre lo sean 💕.",
  "🌙 Hay algo mágico en ti, Esther. Una energía suave pero poderosa que me inspira cada vez más ❤️.",
  "🍃 Eres como ese viento que refresca después de un día caluroso. Llegas y todo se siente en paz 🌿.",
  "🌅 Hoy quiero agradecerte, aunque sea en silencio, por ser parte de mis pensamientos más bonitos 💖.",
  "💫 No hace falta verte todos los días para admirarte; basta con recordarte para que el corazón sonría 💭.",
  "🌸 Cada palabra tuya deja un eco en mi mente, uno de esos que no quiero que se apague ✨.",
  "☀️ Que este mes te regale muchas sonrisas y que la vida te devuelva todo lo bueno que das ❤️.",
  "🌷 Cuando hablas de tus sueños, inspiras. Cuando los cumples, demuestras que todo es posible 💫.",
  "🌻 Eres esa clase de persona que no necesita hacer mucho para hacer que todo sea mejor 🌼.",
  "💖 A veces pienso que el universo tiene su manera de conectar almas bonitas… y por eso te conocí ✨.",
  "🌙 Me encanta cómo puedes ser calma y energía al mismo tiempo. Tienes un equilibrio que simplemente enamora 💕.",
  "☕ Ojalá este día te traiga momentos lindos, risas sinceras y la tranquilidad que mereces 🌅.",
  "💫 Hay cosas que se explican con palabras, pero lo que siento por ti, Esther, se entiende solo con el corazón ❤️.",
  "🌈 Que tu sonrisa sea más fuerte que cualquier preocupación, porque tu felicidad es demasiado valiosa 💕.",
  "🌹 Eres ese tipo de persona que deja huellas, no por lo que hace, sino por lo que transmite 💫.",
  "🌼 No todos los días son fáciles, pero tú haces que incluso los difíciles tengan algo bonito 💖.",
  "💫 Hoy solo quiero recordarte que eres alguien especial, no por lo que haces, sino por lo que eres 🌷.",
  "🌻 Si alguna vez dudas de ti, recuerda que hay alguien que cree en ti más de lo que imaginas ❤️.",
  "☀️ Ojalá que hoy el sol te abrace con la misma calidez con la que tú iluminas mis días 🌻.",
  "🌙 Hay noches que parecen más tranquilas solo porque sé que existes, Esther. Eres calma en medio del caos ✨.",
  "🌷 Cada día trae su propio reto, pero tú tienes una manera hermosa de superarlos: con fortaleza y una sonrisa 💪💖.",
  "🍃 A veces basta con pensar en alguien especial para que el día cambie… y tú siempre logras eso en mí 💫.",
  "💫 Eres como esa brisa suave que llega sin avisar, pero deja paz donde pasa 🌿.",
  "🌹 Nunca dejes que el miedo te detenga, Esther. El mundo necesita esa luz que llevas dentro 🌟.",
  "☕ Que tu día empiece con cosas bonitas, pensamientos buenos y un motivo para sonreír. Si no lo tienes, aquí te dejo uno: tú eres increíble ❤️.",
  "🌈 Hoy quiero recordarte que los días difíciles no duran, pero las personas fuertes como tú siempre resplandecen 💫.",
  "🎶 Si la vida fuera una canción, tú serías la parte más bonita del estribillo 🎧💖.",
  "🌻 No hace falta que el día sea perfecto, basta con que lo vivas con tu esencia tan linda 🌞.",
  "✨ No sé si el universo conspira, pero cada vez que pienso en ti, todo parece alinearse de una forma especial 💕.",
  "🌙 Hay algo mágico en ti, Esther. Una mezcla de ternura, fuerza y calma que me deja sin palabras 🌌.",
  "🌷 Que este día te recuerde lo mucho que vales y todo lo bonito que eres capaz de lograr 💪💫.",
  "☀️ Si supieras lo mucho que inspiras, entenderías por qué hablar de ti siempre se siente como hablar de algo bonito ❤️.",
  "🌸 Eres la razón por la que a veces sonrío sin explicación. Y la explicación eres tú 💕.",
  "💖 Que hoy la vida te devuelva todo lo bueno que das a los demás, multiplicado por mil 🌈.",
  "🌼 No sé si lo notas, pero cuando hablas, transmites calma; cuando sonríes, transmites alegría. Tienes algo especial ✨.",
  "🌙 Las estrellas brillan, pero ninguna como tú cuando crees en ti misma 💫.",
  "🍃 Hay días en los que el corazón se siente lleno, y normalmente es porque pienso en ti 💕.",
  "🌹 No importa lo que el día traiga, recuerda que siempre hay alguien que cree en ti y te admira mucho ❤️.",
  "☕ Hoy quiero desearte serenidad, amor y una razón para sonreír antes de dormir 🌙.",
  "🌻 Abril está lleno de días bonitos, pero ninguno tan especial como tú 🌸.",
  "✨ Hay personas que transforman los momentos simples en recuerdos inolvidables… tú eres una de ellas 💖.",
  "🌅 No sé qué tenga tu presencia, pero siempre logra tranquilizarme. Tienes un efecto que no se explica 💫.",
  "💫 Si hoy dudas de ti, mira lo lejos que has llegado. Tienes más fuerza de la que imaginas 💪🌈.",
  "🌼 Me encanta cómo haces que todo se sienta más ligero, más bonito, más tú 🌻.",
  "🌙 Ojalá supieras lo mucho que significas, Esther. A veces las palabras no alcanzan 💕.",
  "🌸 Cada día contigo, aunque sea a través de un pensamiento, me recuerda que la vida tiene sentido cuando se siente así 💫.",
  "🌞 Cada amanecer trae una oportunidad para ser feliz, y pensar en ti ya hace que el día empiece bien 💕.",
  "✨ Hay personas que iluminan el mundo sin darse cuenta. Tú lo haces cada vez que sonríes 😍.",
  "🌷 No sé si lo notas, pero cuando hablas de lo que te apasiona, tus ojos brillan más que las estrellas 🌟.",
  "☕ Hoy deseo que el día te trate tan bien como tú tratas a los demás, con dulzura, energía y una sonrisa sincera ❤️.",
  "🌙 A veces me basta con mirar la luna y sentir que, de alguna manera, también la estás viendo tú. Es mi forma de estar cerquita 💭.",
  "💫 Que nunca te falte motivación, pero sobre todo, que nunca te falte fe en ti. Eres capaz de lograr todo lo que te propongas 🌈.",
  "🎶 La vida tiene su propia melodía, pero contigo suena mucho mejor 🎧💖.",
  "🌻 Hoy recuerda que el esfuerzo que haces, aunque a veces no se note, siempre deja huella. Estoy muy orgulloso de ti 💪✨.",
  "🌅 Cada tarde pienso en lo bonito que sería compartir un atardecer contigo. Hay cosas que solo se disfrutan más cuando estás tú 💫.",
  "🦋 Eres de esas personas que dejan luz incluso cuando se van. Siempre queda algo bonito después de ti 🌟.",
  "💭 Si tan solo supieras la calma que traes a mis días, entenderías por qué me gusta tanto escribirte 💌.",
  "🌺 No tienes idea de lo mucho que inspiras, Esther. Tienes una forma de ser que le da sentido a todo 🌈.",
  "🌤️ A veces los días pesan, pero saber que estás ahí hace todo más ligero. Eres mi pensamiento bonito del día 💕.",
  "✨ No todos los días son perfectos, pero con tu energía y sonrisa, cualquier día puede mejorar ❤️.",
  "🌙 Si pudiera elegir un pensamiento para empezar cada mañana, siempre serías tú 🌸.",
  "💫 No busques ser perfecta, Esther. Ya brillas siendo auténtica, y eso te hace única 🌹.",
  "🕊️ La vida siempre se ve mejor cuando se mira con esperanza. Y tú, sin darte cuenta, eres una de mis razones para tenerla 🌈.",
  "🌼 Que hoy la vida te abrace con cosas bonitas, con paz, con cariño y con personas que te valoren tanto como yo 💖.",
  "🎇 Hay días normales… y luego hay días en los que apareces tú, y todo se vuelve especial 🌟.",
  "☀️ Recuerda que las cosas más bonitas toman tiempo. Y tú, Esther, eres la prueba de que lo bueno vale la espera 💫.",
  "🍃 No importa cuán rápido vaya el mundo, cada vez que pienso en ti todo se detiene un poco 💭.",
  "🌙 Eres como esa noche tranquila después de un día pesado. Llegas y todo tiene sentido 💕.",
  "💐 Me encanta cómo puedes ser fuerza y ternura al mismo tiempo. Eres equilibrio, y eso te hace maravillosa 🌻.",
  "🌈 A veces el corazón se llena sin explicación, y creo que el mío lo hace cada vez que pienso en ti 💞.",
  "🌅 El universo tiene su manera de sorprendernos, pero sin duda, la mejor sorpresa fue encontrarte ✨.",
  "🌺 Que hoy te acompañe la paz, la confianza y esa sonrisa tuya que tanto me gusta ver 💫.",
  "🌙 Si el cielo hablara, contaría la historia de una persona increíble que brilla más que cualquier estrella 💖.",
  "☕ Este mes apenas comienza, y ya estoy deseando que cada día sea tan bonito como tú ❤️.",
  "🌻 Cada día contigo —aunque sea en pensamiento— me enseña algo nuevo sobre lo que significa admirar a alguien 💫.",
  "Hay personas que hacen que todo valga la pena solo con su forma de ser… y tú eres una de ellas ❤️",
  "Eres ese tipo de persona que transmite paz incluso sin decir una palabra 🌿✨",
  "A veces no hacen falta grandes gestos, basta con pensar en ti para que todo se sienta mejor 🌸",
  "Tu risa tiene ese poder de hacer que cualquier día se vuelva especial 💫",
  "Nunca dejes de creer en ti, porque eres capaz de todo lo que te propongas 💪🏼🌟",
  "Hay algo en ti que simplemente me inspira, no sé si es tu forma de ver la vida o la luz que irradias 💖",
  "Eres la prueba de que las personas bonitas no solo existen, también iluminan la vida de otros 🌞",
  "Cada detalle tuyo me hace admirarte un poco más, porque tienes algo que no se encuentra todos los días ✨",
  "Espero que hoy recibas la misma alegría que tú provocas en los demás ❤️",
  "Eres un recordatorio constante de que la bondad y la dulzura siguen existiendo 🌷",
  "Hay miradas que calman, palabras que abrazan y personas que marcan… tú haces las tres 💫",
  "Si hoy sientes que el mundo va muy rápido, respira… estás haciendo las cosas mejor de lo que crees 🌿",
  "Nunca olvides lo mucho que vales, porque hay corazones que sonríen solo con pensar en ti ❤️",
  "Tu forma de ver la vida me enseña que la ternura también puede ser fuerza 🌸",
  "Eres esa razón que hace que los días comunes se vuelvan inolvidables 💫",
  "Tienes una energía tan bonita que hasta los días grises parecen llenos de color cuando estás cerca 🌈",
  "A veces pienso que si existieran más personas como tú, el mundo sería un lugar mucho más bonito 🌍💖",
  "Cada vez que sonríes, hay un pedacito del mundo que se vuelve mejor 🌟",
  "Hay algo especial en ti que no sé describir, pero me hace querer cuidar de ti siempre 🫶🏼",
  "Eres esa inspiración que llega sin avisar, pero se queda en cada pensamiento 🌙",
  "Si supieras todo lo bonito que inspiras sin darte cuenta, te sonreirías cada mañana 💕",
  "Tu presencia deja una paz que ni las palabras pueden explicar 💫",
  "No importa el lugar ni el momento, pensar en ti siempre me da calma 🌿",
  "Hay personas que llegan a la vida para quedarse en el alma… y tú ya tienes un lugar ahí ❤️",
  "Eres ese pensamiento bonito que aparece en medio del caos y me hace sonreír sin razón ✨",
  "Que nada te quite esa luz tan tuya, la que ilumina todo sin esfuerzo 🌸",
  "Contigo aprendí que las cosas simples pueden ser las más hermosas 💫",
  "Eres una de esas personas que no necesitan hacer mucho para dejar huella, simplemente siendo tú 💖",
  "No sé si fue casualidad o destino, pero tenerte en mi vida es algo que valoro cada día 🌙",
  "Hay personas que marcan un antes y un después… tú definitivamente eres una de ellas 💫",
  "A veces no sé cómo explicarlo, pero pensar en ti siempre logra tranquilizarme 💫 eres como un respiro entre tanto ruido 🌿",
  "Me encanta la forma en que logras brillar sin intentarlo, simplemente siendo tú 🌞",
  "Hay personas que llenan de color la vida de otros, tú hiciste eso conmigo 🎨❤️",
  "No sé si lo notas, pero cuando hablo contigo todo se siente más ligero ✨",
  "Tu energía es tan bonita que incluso a la distancia se siente 🌙💖",
  "Contigo aprendí que las conexiones genuinas no necesitan mucho para sentirse reales 💫",
  "Eres esa razón que convierte un día común en algo que vale la pena recordar 💕",
  "Tienes un no sé qué… que me inspira, me calma y me encanta 🌸",
  "Hay miradas que dicen más que mil palabras, y la tuya tiene un idioma propio ❤️",
  "Cada vez que sonríes, todo alrededor parece detenerse por un instante ✨",
  "Tu presencia tiene algo que me hace querer ser una mejor versión de mí mismo 🌿",
  "Eres la persona con la que los silencios también se sienten cómodos 💫",
  "Si supieras todo lo que inspiras sin darte cuenta, entenderías por qué siempre pienso en ti 💭💖",
  "Tu forma de ver el mundo me recuerda lo hermoso que es encontrar belleza en lo simple 🌷",
  "A veces basta un solo mensaje tuyo para mejorar todo mi día 💫",
  "Hay algo en ti que me hace querer cuidar cada detalle, cada momento, cada palabra 🫶🏼",
  "Tú no solo eres importante, eres esa calma que me acompaña incluso cuando no estás 🌙",
  "Eres una de esas personas que se ganan un lugar en el corazón sin pedirlo 💕",
  "Cada conversación contigo deja una sensación bonita, como si el día tuviera más sentido ✨",
  "Hay personas que inspiran sin darse cuenta, y tú eres una de ellas 🌸",
  "Eres esa paz que aparece cuando todo parece ir demasiado rápido 🌿💫",
  "No hay forma de no pensar en ti cuando todo lo que haces transmite tanto ❤️",
  "Tu forma de ser tiene esa magia que no se puede explicar, solo admirar 🌙",
  "Eres el tipo de persona que merece todo lo bonito que la vida pueda dar 💕",
  "Si supieras la sonrisa que provocas cada vez que te recuerdo, entenderías lo especial que eres ✨",
  "Hay días en los que simplemente me alegra saber que existes 💫",
  "Tu luz no solo ilumina tu camino, también el de quienes tienen la suerte de conocerte 🌞",
  "No necesitas ser perfecta, ya eres maravillosa siendo tú misma ❤️",
  "Eres esa persona que no esperaba, pero que ahora no quiero que falte 💫",
  "Gracias por ser tú, por inspirar, por hacer que cada día tenga algo bonito que recordar 🌸",
  "A veces olvidas lo mucho que vales, pero quiero recordarte que eres capaz de lograr cualquier cosa que te propongas 💪🏼✨",
  "Tu esfuerzo diario es una inspiración 🫶🏼, incluso cuando crees que nadie lo nota, tu dedicación brilla más de lo que imaginas 🌟",
  "Eres una persona increíblemente inteligente y constante, no subestimes el poder que tienes para cambiar tu entorno 💫",
  "Hay días difíciles, pero tú tienes una fuerza interior que hace que todo sea posible ❤️",
  "Cada paso que das, por pequeño que parezca, te acerca a tus sueños 🌙 no te rindas nunca 🌸",
  "Tu determinación es admirable, y tu corazón hace que todo lo que haces tenga un propósito más bonito 💕",
  "No necesitas demostrarle nada a nadie, ya haces suficiente solo con ser tan genuina y esforzada 🌿",
  "Recuerda siempre: el mundo necesita más personas con tu responsabilidad, tu dulzura y tu compromiso 🌞",
  "Tienes una mente brillante y un corazón enorme, una combinación que siempre te llevará lejos ✨",
  "Cuando dudes de ti, piensa en todo lo que ya lograste, en todo lo que superaste y en lo fuerte que eres 💪🏼",
  "Hay pocas personas con tanta pasión por lo que hacen como tú 🌸 sigue brillando, tu camino es único 💫",
  "Tu disciplina es impresionante, pero lo que más me inspira es cómo haces todo con cariño y entrega 💖",
  "A veces no lo ves, pero estás construyendo algo grande, paso a paso, con esfuerzo y corazón 🌿✨",
  "Tu capacidad para salir adelante incluso en los días grises es algo que admiro profundamente 🌙",
  "Tienes una inteligencia tan natural que hace que todo lo que tocas se vuelva aprendizaje y crecimiento 🌻",
  "Nunca dejes que los tropiezos te hagan dudar de tu valor, porque tú puedes con todo 💪🏼💫",
  "Eres el tipo de persona que no solo sueña, sino que trabaja por hacer realidad esos sueños 🌟",
  "Tu responsabilidad es admirable, pero no olvides también cuidar de ti y celebrar tus logros ❤️",
  "Cuando sientas cansancio, recuerda que tu esfuerzo vale cada segundo, y que vas por un camino hermoso 🌷",
  "Eres más fuerte de lo que imaginas y más capaz de lo que crees 💕 confía en ti, siempre 🌙",
  "Tu constancia y compromiso hacen la diferencia, aunque a veces no lo veas ✨ sigue así, vas increíble 🌻",
  "Hay algo muy bonito en ti: haces todo con amor, y eso se nota en cada resultado 💫",
  "Tu esfuerzo no pasa desapercibido, eres ejemplo de lo que significa trabajar con pasión 🌟",
  "Incluso cuando dudas, sigues avanzando, y eso es lo que te hace verdaderamente admirable 💪🏼",
  "No todos tienen la determinación que tú tienes, por eso estoy tan orgulloso de ti 💖",
  "Tu mente es poderosa, tu corazón noble y tu camino, simplemente inspirador 🌸",
  "A veces los logros más grandes llegan después de los días más difíciles 🌙 y tú sabes cómo superarlos todos 💫",
  "Sigue creyendo en ti como yo creo en ti ❤️, porque lo que viene será aún más increíble ✨",
  "Tu capacidad para hacer que todo funcione, incluso cuando parece imposible, es realmente admirable 🌿",
  "No importa lo lejos que llegues, siempre recuerda esto: eres extraordinaria por lo que haces y por lo que eres 💕",
  "Sé que a veces el día puede sentirse largo, pero quiero que recuerdes que no estás sola 💫, hay personas que te admiramos más de lo que imaginas ❤️",
  "Respira, vas increíble 🌿 a veces no lo notas, pero estás haciendo un trabajo maravilloso solo con seguir adelante ✨",
  "No necesitas tenerlo todo bajo control; tu esencia y tu esfuerzo ya hacen que todo salga bien 💕",
  "Hay días que pesan, pero tú tienes un corazón fuerte y una mente brillante 🌙 nunca lo olvides 💫",
  "Cuando el cansancio llegue, recuérdate que mereces descansar tanto como te esfuerzas ❤️",
  "A veces el mundo va muy rápido, pero tú sabes mantener la calma y eso te hace especial 🌿",
  "No importa cuán difícil se ponga el día, tú siempre logras salir adelante con una sonrisa ✨",
  "Tu forma de enfrentar los retos con serenidad es algo que admiro profundamente 💖",
  "Aunque hoy no lo veas, estás dejando huellas bonitas en cada paso que das 🌸",
  "Eres más fuerte de lo que crees, y más valiente de lo que imaginas 🌙💫",
  "Cuando dudes de ti, piensa en todas las veces que lograste lo que parecía imposible 💪🏼✨",
  "Hay personas que transmiten calma solo con existir… y tú eres una de ellas ❤️",
  "Tu capacidad para mantener la esperanza incluso en los días nublados es algo hermoso 🌧️💫",
  "Hoy mereces una pausa, un respiro, y un recordatorio: lo estás haciendo increíble 🌿",
  "Eres de esas personas que inspiran sin decir una palabra, solo siendo ellas mismas 💕",
  "Tu energía tiene algo especial, porque siempre logras iluminar hasta los días más grises 🌙",
  "Nunca subestimes el poder de tus pequeños logros, son los que te están llevando lejos ✨",
  "A veces la vida se complica, pero tú siempre encuentras la forma de sonreír 🌸 y eso tiene mucho valor 💫",
  "Eres constancia, bondad y luz, y eso te hace alguien que deja huella donde va 🌞",
  "Cuando el cansancio aparezca, recuerda que mereces tanto como das ❤️",
  "No hay reto que no puedas superar, porque tu fuerza va más allá de lo que crees 💪🏼✨",
  "Tu corazón noble y tu mente brillante son la combinación más poderosa 🌿",
  "Hay días difíciles, sí… pero tú tienes esa magia de volverlos más llevaderos con tu actitud 💫",
  "Tu esfuerzo no pasa desapercibido, y tu dedicación siempre será motivo de admiración 💕",
  "No dejes que el estrés opaque lo hermosa que eres en todos los sentidos 🌙✨",
  "Tu forma de cuidar de todo y de todos es admirable, pero no olvides cuidarte a ti también ❤️",
  "La vida te puso retos porque sabía que podías con ellos 🌻 y vaya que lo estás demostrando 💫",
  "Eres la calma en medio del caos, la sonrisa en medio del cansancio 🌿",
  "Tu historia está llena de logros silenciosos que valen más de lo que imaginas 💕",
  "No importa lo que pase hoy, recuerda: eres increíble, y no hay duda de eso 🌙💫",
  "Tienes una forma tan especial de iluminar los días, que incluso los más grises se vuelven cálidos cuando pienso en ti ☀️❤️",
  "Eres una mezcla perfecta de fortaleza y ternura, alguien que inspira solo con ser 🕊️✨",
  "Tu esfuerzo y dedicación me motivan todos los días, porque ver cómo das lo mejor de ti es realmente admirable 🌿💫",
  "Nunca olvides que eres capaz de todo lo que te propongas, incluso de aquello que hoy parece muy lejos 🌙💪🏼",
  "Tu sonrisa tiene el poder de cambiar cualquier día, y eso te hace simplemente única 🌻❤️",
  "Hay personas que inspiran con palabras, pero tú inspiras con tus actos y tu corazón 💕",
  "Eres una de esas personas que hacen que todo valga la pena, incluso los días difíciles 🌙💫",
  "Tenerte en mi vida me recuerda que lo bonito sí existe y que vale la pena cuidarlo 🌼",
  "Tu presencia es calma, es fuerza y es motivo de alegría, no importa el día ni la hora 🌿✨",
  "Cuando te miro, entiendo por qué el universo se toma su tiempo para crear cosas tan bonitas 💫❤️",
  "Ojalá pudieras verte como yo te veo: capaz, brillante y con un corazón inmenso 💕",
  "A veces pienso que el mundo se detiene solo para admirar la paz que transmites 🌙✨",
  "Tu forma de ser me inspira a querer ser mejor, no por obligación, sino porque tú lo haces natural 💫",
  "No hay un solo día en que deje de admirar tu fuerza y la manera tan linda en que enfrentas todo ❤️",
  "Eres esa persona que convierte lo simple en especial y lo común en algo mágico 🌸✨",
  "Aun en tus días más cansados, sigues brillando de una forma que no se apaga 🌙💫",
  "Eres inspiración, ternura y un recordatorio constante de que el amor se demuestra con detalles 💕",
  "Si el mundo fuera tan noble y constante como tú, todo sería más bonito 🌿💫",
  "Tu forma de cuidar, de esforzarte, de sonreír… todo en ti tiene algo que conmueve 🌻❤️",
  "No necesitas hacer mucho para ser especial, porque ya lo eres solo con ser tú 💫",
  "Eres el tipo de persona que deja huella incluso sin darse cuenta 🌸✨",
  "Tu determinación es tan fuerte como tu corazón es noble 💕 y eso te hace increíble",
  "Cada logro tuyo es una muestra de lo mucho que puedes lograr cuando crees en ti 💪🏼🌙",
  "El mundo necesita más personas como tú: comprometidas, sensibles y llenas de luz ❤️",
  "A veces pienso que la vida me sonrió al ponerte en mi camino 🌿✨",
  "Tu energía transforma los lugares, las personas y los momentos 🌙💫",
  "Eres constancia, dulzura y amor, todo en perfecta armonía 💕",
  "Ojalá nunca dudes del impacto tan bonito que tienes en quienes te rodean 🌻❤️",
  "Tu esfuerzo me inspira, tu sonrisa me calma y tu forma de ser me enamora 🌙✨",
  "Eres esa persona que sin decir mucho, lo dice todo 💫❤️",
  "Cree en ti, incluso cuando nadie(yo siempre creere en todo que te propongas, siempre contaras con mi apoyo) más lo haga.",
  "Cada paso, por pequeño que parezca, te acerca a donde quieres estar. Recuerda que todo suma❤️",
  "Hoy quiero recordarte que vas por el camino correcto. Aunque a veces dudes o te sientas cansada, no olvides todo lo que has logrado. Eres fuerte, valiente y capaz de llegar mucho más lejos de lo que imaginas. 🌷",
  "No importa cuántas veces hayas caído, lo que realmente cuenta es que sigues intentándolo. Eso habla de tu fuerza y de ese corazón enorme que no se rinde. 💪❤️",
  "La vida no siempre es fácil, pero tú tienes una luz especial que hace que todo valga la pena. Sigue brillando, sigue creyendo, y nunca olvides lo increíble que eres. ✨",
  "A veces el mundo puede ser ruidoso, pero quiero que sepas que tu esfuerzo, tu bondad y tu sonrisa hacen una gran diferencia. No dejes de ser tú. 🌸",
  "Has superado tanto, y aun así sigues dando lo mejor de ti. Eso es admirable. Que hoy te abraces con orgullo y te recuerdes lo valiosa que eres. 💛",
  "No todo sale como esperamos, pero lo importante es no perder la fe en ti. Tienes la fuerza, la inteligencia y el corazón para lograr cosas hermosas. 🌈",
  "Incluso en los días difíciles, hay algo en ti que sigue brillando. Esa fuerza interior que te levanta una y otra vez merece todo el reconocimiento. 🌻",
  "No te castigues por lo que no salió, agradécete por todo lo que hiciste para intentarlo. Eres maravillosa, incluso cuando dudas de ti. 💖",
  "Cada día que eliges continuar, aunque estés cansada, ya estás ganando. Eso es coraje, eso es amor propio. 🌷",
  "Recuerda que no estás sola; hay personas que creen en ti, que admiran tu esfuerzo y que se inspiran con tu manera de ser. ❤️",
  "Eres una persona increíble: fuerte, noble, sensible y con una mente brillante. Nunca subestimes el poder de todo lo que eres. 💫",
  "Si hoy las cosas se sienten pesadas, tómate un respiro y recuerda que estás haciendo lo mejor que puedes. Y eso, créeme, ya es suficiente. 🌼",
  "Que nunca te falte la fe en ti misma, ni la ternura para seguir intentando. Lo estás haciendo bien, incluso cuando no lo notas. 💛",
  "A veces el corazón se cansa, pero siempre encuentra un motivo para seguir. El tuyo es grande, valiente y lleno de amor. 💖",
  "No necesitas ser perfecta para merecer cosas bonitas. Ya eres suficiente, ya eres luz, y ya estás dejando huella. 🌸",
  "Hoy no te exijas tanto, solo mírate con cariño y reconoce todo lo que has logrado. Eres una historia de superación en movimiento. 🌟",
  "Lo que haces cada día, aunque parezca pequeño, tiene un valor enorme. Tu esfuerzo inspira más de lo que imaginas. 💕",
  "Que este día te recuerde lo lejos que has llegado, y todo lo que puedes seguir alcanzando si sigues creyendo en ti. 🌈",
  "Eres esa clase de persona que convierte lo difícil en posible, y lo cotidiano en algo hermoso. Nunca cambies. 💛",
  "Tal vez hoy no tengas todas las respuestas, pero sí tienes el corazón, la fuerza y la luz para seguir avanzando. 🌻",
  "No olvides agradecerte por seguir aquí, por no rendirte, por darte amor incluso cuando nadie más lo ve. ❤️",
  "A veces el paso más pequeño hacia adelante es el más valiente. Y tú das esos pasos todos los días, con fuerza y con fe. 💫",
  "Qué bonito es verte crecer, aprender, sanar y seguir brillando. La persona que eres hoy merece todo lo bueno que viene. 🌷",
  "No te detengas ahora. El camino no ha sido fácil, pero tu corazón ha demostrado que puede con todo. 💪",
  "Que nunca se te olvide: vales mucho, importas mucho, y el mundo es mejor con tu sonrisa en él. 💖",
  "La vida tiene altibajos, pero tu espíritu constante y tu bondad son lo que hacen que todo cobre sentido. 🌼",
  "Cada día es una nueva oportunidad para empezar otra vez, para creer de nuevo, para amarte un poco más. 🌈",
  "Eres una mezcla hermosa de fuerza y ternura, de sueños y realismo. Y eso te hace simplemente única. 💛",
  "No te apresures; las cosas buenas también tardan. Lo importante es que sigues caminando con el corazón por delante. 🌸",
  "Que este día te abrace con calma, te llene de esperanza y te recuerde que eres más increíble de lo que imaginas. ❤️✨",
  "Quiero que no se te olvide nunca que estoy a tu lado, para todo lo que necesites ❤️✨. Pero quiero que tampoco olvidez que eres capaz de todo y que crep en ti con todas mis fuerzas❤️✨.",
  "Tiempo al tiempo⏳, que las cosas buenas van llegando solitas y poco a poco💫.",
  "Échale ganas, sé que andas con cansancio, estrés y bajones, pero solo son rachitas. Recuerda que eres fuerte, inteligente y que puedes con todo❤️",
  "El mundo tiene sus maravillas, pero tu eres la maravilla de mi mundo🌎🥰",
  "No te falta nada. Eres una gran mujer, un amor de persona, eres trabajadora, estás preciosa, te esfuerzas cada día y tu ❤️ es noble. No dudes de ti :).",
  "Eres una niña muy linda, hermosa, guapa, valiosa, maravillosa, tu coranzoncito vale oro más que el oro y jamas digas que no, eres espectacular, acuerdate que a tráves de mis ojos siempre seras serás unica❤️",
  "Eres fuerte, eres valiosa y eres especial. La vida te puso retos, pero también te dio un alma que no se rinde y eso es lo que te hace unica💪💫.",
  "No todas las estrellas se encuentran en el cielo, algunas están aqui, sobre la tierra, en tu mirada por ejemplo😍",
  "Lo que siento por ti no cabe en palabras, ni en versos, ni en canciones. Es algo que se siente en la piel, en el alma, en los silencios compartidos. Eres el pensamiento que calma, la voz que me devuelve el sentido, la historia que no quiero que acabe. Porque cuando te miro, lo entiendo todo: esto... es amor, del que no se olvida.",
  "Mientras te criticas por no avanzar, recuerda que hay alguien que admira lo que has logrado.🤭",
  "Mientras te preguntas si estás haciendo lo suficiente, recuerda que hay alguien que se pregunta cómo puedes hacerlo todo✨",
  "Gracias por ser como erés, por tu amistad y por demostrarme que en este mundo aún hay personas bonitas en las que podemos confiar, TE QUIERO MUCHO🥰",
  "❤️TE QUIERO MUCHO❤️✨, MÁS DE LO QUE TE IMAGINAS❤️",
  "Hoy dibuja una sonrisa😁 en esa carita hermosa que te dió Dios. Bella y maravillosa ya eres✨",
  "No te falta nada. Eres una gran mujer, un amor de persona, eres trabajadora, estás guapisima, te esfuerzas todos los días y tu corazón es noble, no dudes de ti✨❤️",
  "Hoy es un buen día para recordarte que mereces todo lo que sueñas y que eres capaz de lograr todo lo que te propongas. Lo mejor esta por venir...",
  "Que jamas se te olvide que tú eres de personas bonitas que inspiran, que curan, que brillan y que son chingonas del corazón, de la sonrisa y de cada centimetro de su alma...",
  "Eres bonita, hermosa, maravillosa, tienes unos ojos preciosos, un cabello hermoso y una sonrisa tan encantadora💕",
  "Eres mágica, tierna, bonita, maravillosa, hermosa, poesia, fuego, estrellas, eres la chica que no aparenta mucho, pero del alma eres una galaxia entera...🌌",
  "Tú para mi eres perfecta, bella, incomparable, linda y sobre todo la niña más hermosa del mundo💕",
  "Gracias por compartir un rato de tu vida conmigo, por hacerme reir, por darle un giro a mi mundo. Gracias por cruzarte en mi camino...✨",
  "Te quiero💕 asi como eres. Con todo lo bueno que no ves y con todo lo malo que dices tener...",
  "Espera... No te vayas... Tengo algo... Que decirte... Gracias por cruzarte en mi vida. TE QUIERO MUCHO❤️",
  "Me dijieron: \"Piensa en algo que te haga feliz\". Y te imagine a ti, SONRIENDO🤭",
  "Que cada luz encendida esta noche te recuerde lo valiosa que eres. 🤍",
  "Que los días grises se llenen de brillo y los buenos momentos duren más. ✨",
  "Que el amor, la calma y las sonrisas te acompañen en cada paso. 🌟",
  "Que esta fecha te envuelva con la misma luz que tú regalas al mundo. 🌙✨",
  "Que cada estrella del cielo celebre tu forma tan bonita de ser. ⭐",
  "Que encuentres descanso, paz y alegría en los pequeños detalles. 🤍",
  "Que el calor de esta noche te recuerde que eres profundamente especial. ❄️🤍",
  "Admiro la manera en que sigues adelante, incluso cuando el camino no es fácil tu esfuerzo habla más fuerte que cualquier palabra.✨",
  "Tu constancia y tu forma de enfrentar la vida son un reflejo de la gran persona que eres.🤍",
  "Hay una fortaleza silenciosa en ti que inspira, una que se construye día a día con esfuerzo y corazón.",
  "Todo lo que logras tiene detrás dedicación, valentía y una esencia muy bonita que te define.",
  "Tu esfuerzo no pasa desapercibido; se nota en lo que haces y en la persona en la que te conviertes.✨",
  "Eres ejemplo de que la sensibilidad y la fuerza pueden caminar juntas.🤍"
];

if (isChristmas(true)) {
  appPhrases = [
    "Solo quería desearte una muy linda Nochebuena y una Navidad llena de paz, luz y momentos bonitos. 🎄✨ Que esta noche esté rodeada de calma, sonrisas y personas que te quieren, y que cada instante te regale tranquilidad, cariño y razones para sonreír. Disfruta mucho estas fechas tan especiales. 🤍✨",
    "Esther, que la luz de esta Navidad 🎄 ilumine cada paso que das y te recuerde lo valiosa que eres 🌟",
    "En estas fechas tan bonitas 🎄, deseo que recibas todo el cariño que das cada día 🤍",
    "Que el espíritu navideño 🎄 te llene de paz, esperanza y motivos para sonreír ✨",
    "Navidad es pausa, es luz 🎄, y tú haces que todo brille un poquito más 🌙",
    "Que esta Navidad 🎄 te regale descanso al alma y alegría al corazón 💫",
    "Esther, que cada lucecita de Navidad 🎄 te recuerde lo especial que eres ✨",
    "En esta Navidad 🎄, que nunca te falte amor, calma y sueños bonitos 🤍",
    "Que los días navideños 🎄 te abracen suave y te llenen de esperanza 🌟",
    "Navidad 🎄 también es agradecer, y yo agradezco que existas ✨",
    "Que esta época tan linda 🎄 te regale momentos simples pero inolvidables 💖",
    "Esther, que la magia de la Navidad 🎄 te acompañe hoy y siempre ✨",
    "Que cada noche de diciembre 🎄 esté llena de paz y pensamientos bonitos 🌙",
    "Navidad 🎄 es compartir luz, y tú tienes mucha para dar 🌟",
    "Que esta Navidad 🎄 llegue cargada de calma, ilusión y sonrisas sinceras ✨",
    "Esther, que el amor de estas fechas 🎄 te rodee y te haga sentir en casa 🤍",
    "Que los pequeños momentos de Navidad 🎄 se conviertan en grandes recuerdos 💫",
    "Navidad 🎄 es creer, y tú inspiras a creer en cosas bonitas ✨",
    "Que esta Navidad 🎄 te regale motivos nuevos para sonreír 🌟",
    "Esther, que el brillo de estas fechas 🎄 refleje todo lo bonito que hay en ti ✨",
    "Que el calor de la Navidad 🎄 llegue directo a tu corazón 🤍",
    "Navidad 🎄 es luz en medio del invierno, como tu sonrisa 🌙",
    "Que esta Navidad 🎄 te traiga tranquilidad, amor y sueños en paz ✨",
    "Esther, que cada abrazo navideño 🎄 te recuerde lo querida que eres 💖",
    "Navidad 🎄 también es agradecer lo vivido y confiar en lo que viene 🌟",
    "Que la magia de estas fechas 🎄 te llene de esperanza y serenidad ✨",
    "Esther, que esta Navidad 🎄 sea tan bonita como tu esencia 🤍",
    "Que los días navideños 🎄 te regalen paz, risas y descanso 🌙",
    "Navidad 🎄 es corazón, y tú tienes uno muy bonito ✨",
    "Que esta Navidad 🎄 te recuerde lo fuerte, valiosa y especial que eres 🌟"
  ];
}
